#!/usr/bin/env python
import rospy
from std_msgs.msg import String
from geometry_msgs.msg import *


def talker():
    pub = rospy.Publisher('object_position', geometry_msgs.msg.PoseStamped)
    rospy.init_node('simu_object_position')
    r = rospy.Rate(40) # 40hz
    while not rospy.is_shutdown():
        msg = geometry_msgs.msg.PoseStamped()
        msg.header.stamp = rospy.Time.now()
        pub.publish(msg)
        r.sleep()

if __name__ == '__main__':
    try:
        talker()
    except rospy.ROSInterruptException:
        pass
